import "@/styles/globals.css";
import Navigation from "./sections/Navigation";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="font-sans">
				<Navigation />
				{children}
			</body>
		</html>
	);
}
